apiVersion: v1
kind: Service
metadata:
  labels:
    app: apex-operator
  name: apex-ctx-sh-webhook
  namespace: apex-system
spec:
  type: NodePort
  ports:
    - port: 9443
      protocol: TCP
      targetPort: 9443
      nodePort: 30100
  selector:
    name: apex-operator
