apiVersion: apex.ctx.sh/v1
kind: Scraper
metadata:
  name: scraper
  labels:
    app: scraper
    service: apex
spec:
  selector:
    matchLabels:
      # k8s-app: kube-proxy
  allowLabels: true
  annotationPrefix: apex.ctx.sh
  metaTags:
    name: true
    namespace: true
    resourceVersion: true
    node: true
  outputs:
    logger:
      enabled: true
    statsd:
      enabled: true
      host: ddagent.example.svc
      port: 8125
