apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base
patchesStrategicMerge:
- deployment.yaml
- webhook.yaml

secretGenerator:
  - name: apex-ctx-sh-webhook-tls
    namespace: apex-system
    files:
      - tls.crt
      - tls.key
    type: "kubernetes.io/tls"

generatorOptions:
  disableNameSuffixHash: true
