apiVersion: v1
kind: Namespace
metadata:
  name: apex
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: apex
  namespace: apex
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: apex
  namespace: apex
subjects:
- kind: ServiceAccount
  name: apex
  namespace: apex
roleRef:
  kind: ClusterRole
  name: apex-role
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dev
  namespace: apex
  labels:
    app: dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dev
  template:
    metadata:
      labels:
        app: dev
    spec:
      serviceAccountName: apex
      containers:
      - name: dev
        image: golang:latest
        imagePullPolicy: Never
        workingDir: /usr/src/app
        command:
          - sleep
          - "3600"
        ports:
        - containerPort: 9090
        volumeMounts:
        - name: app
          mountPath: /usr/src/app
      volumes:
      - name: app
        hostPath:
          path: /app