/*
 * Copyright 2021 Rob Lyon <rob@ctxswitch.com>
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *   http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// Code generated by informer-gen. DO NOT EDIT.

package v1

import (
	"context"
	time "time"

	apexctxshv1 "ctx.sh/apex-operator/pkg/apis/apex.ctx.sh/v1"
	versioned "ctx.sh/apex-operator/pkg/client/clientset/versioned"
	internalinterfaces "ctx.sh/apex-operator/pkg/client/informers/externalversions/internalinterfaces"
	v1 "ctx.sh/apex-operator/pkg/client/listers/apex.ctx.sh/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
)

// ScraperInformer provides access to a shared informer and lister for
// Scrapers.
type ScraperInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() v1.ScraperLister
}

type scraperInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
	namespace        string
}

// NewScraperInformer constructs a new informer for Scraper type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewScraperInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredScraperInformer(client, namespace, resyncPeriod, indexers, nil)
}

// NewFilteredScraperInformer constructs a new informer for Scraper type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredScraperInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options metav1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.ApexV1().Scrapers(namespace).List(context.TODO(), options)
			},
			WatchFunc: func(options metav1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.ApexV1().Scrapers(namespace).Watch(context.TODO(), options)
			},
		},
		&apexctxshv1.Scraper{},
		resyncPeriod,
		indexers,
	)
}

func (f *scraperInformer) defaultInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredScraperInformer(client, f.namespace, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, f.tweakListOptions)
}

func (f *scraperInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&apexctxshv1.Scraper{}, f.defaultInformer)
}

func (f *scraperInformer) Lister() v1.ScraperLister {
	return v1.NewScraperLister(f.Informer().GetIndexer())
}
