apiVersion: v1
kind: Service
metadata:
  labels:
    app: app
  name: app
  namespace: example
spec:
  ports:
    - port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    app: app
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app
  namespace: example
  labels:
    app: app
    group: example
spec:
  replicas: 3
  selector:
    matchLabels:
      app: app
  template:
    metadata:
      labels:
        app: app
        group: example
      annotations:
        apex.ctx.sh/scrape: "true"
        apex.ctx.sh/labels: group
    spec:
      containers:
      - name: app
        image: golang:latest
        imagePullPolicy: Never
        workingDir: /usr/src/app
        command:
          - go
          - run
          - ./config/examples/main.go
        ports:
        - containerPort: 9000
        volumeMounts:
        - name: app
          mountPath: /usr/src/app
      volumes:
      - name: app
        hostPath:
          path: /app